pticostaricags/FairPlaySocial

src/FairPlaySocialSln/FairPlaySocial.ClientServices/ApplicationUserClientService.cs
src/FairPlaySocialSln/FairPlaySocial/Client/CustomClaims/CustomAccountClaimsPrincipalFactory.cs
src/FairPlaySocialSln/FairPlaySocial/Client/Pages/Authentication.razor

Adding place holders for authentication steps.
Improving error handling when creating roles claims in web client app

Adding UI draft improvements

---

src/FairPlaySocialSln/FairPlaySocial.SharedUI/Components/PostComponent.razor

Created a new div for post header
Added missing loading indicator

Fixing issue of modal not showing when clicking on author

---

src/FairPlaySocialSln/FairPlaySocial.SharedUI/Components/PostComponent.razor

Merging fix for post author modal

Merge development into main

---

src/FairPlaySocialSln/FairPlaySocial.CustomValidation/CustomValidationAttributes/ProhibitDuplicateStrings.cs
src/FairPlaySocialSln/FairPlaySocial.Models/Post/CreatePostModel.cs
src/FairPlaySocialSln/FairPlaySocial.SharedUI/Pages/User/Posts/CreateMyPost.razor

Adding custom property and custom validation attribute to evaluate tags duplication.
Fixes #39

Prohibiting duplicate tags when creating posts

---

src/FairPlaySocialSln/FairPlaySocial.MAUIBlazor/MauiProgram.cs
src/FairPlaySocialSln/FairPlaySocial/Client/Program.cs

Enabling support for Http/3 in the web and mobile client apps.
Solves #44

Adding support for Http/3

---

src/FairPlaySocialSln/FairPlaySocial.Database/dbo/Tables/Group.sql
src/FairPlaySocialSln/FairPlaySocial.Database/dbo/Tables/GroupMember.sql

Requires https://github.com/pticostaricags/FairPlaySocial/issues/42 to be implemented
Create a new table named GroupMember, with the following columns
GroupId
MemberApplicationUserId
IOriginatorInfo interface columns
#43

Tarun samanta/43

---

src/FairPlaySocialSln/FairPlaySocial.ClientServices/MyPostClientService.cs
src/FairPlaySocialSln/FairPlaySocial.SharedUI/Components/Feed.razor
src/FairPlaySocialSln/FairPlaySocial.SharedUI/Components/Feed.razor.cs
src/FairPlaySocialSln/FairPlaySocial.SharedUI/Components/PostComponent.razor
src/FairPlaySocialSln/FairPlaySocial.SharedUI/Components/PostComponent.razor.cs
src/FairPlaySocialSln/FairPlaySocial.SharedUI/Pages/User/Posts/Post.razor
src/FairPlaySocialSln/FairPlaySocial.SharedUI/Pages/User/Posts/Post.razor.cs
src/FairPlaySocialSln/FairPlaySocial/Server/Controllers/MyPostController.cs

Enabling transaction-based functionality to delete owned posts

Enable deleting posts

---

src/FairPlaySocialSln/FairPlaySocial.Database/dbo/Tables/PostReach.sql

Created PostReach Table.
#61 
@tarunsamanta2k20

 Created PostReach table

---

src/FairPlaySocialSln/FairPlaySocial.Database/dbo/Tables/GroupModerator.sql

Created GroupModerator table.
#59 
@tarunsamanta2k20

 Created GroupModerator table

---

src/FairPlaySocialSln/FairPlaySocial.ClientsConfiguration/ClientsInitialization.cs
src/FairPlaySocialSln/FairPlaySocial.Services/FairPlaySocial.Services.csproj
src/FairPlaySocialSln/FairPlaySocial.Services/TranslationService.cs
src/FairPlaySocialSln/FairPlaySocial/Client/Extensions/WebAssemblyHostExtensions.cs
src/FairPlaySocialSln/FairPlaySocial/Client/FairPlaySocial.Client.csproj
src/FairPlaySocialSln/FairPlaySocial/Client/Program.cs
src/FairPlaySocialSln/FairPlaySocial/Client/Shared/CultureSelector.razor
src/FairPlaySocialSln/FairPlaySocial/Client/Shared/CultureSelector.razor.cs
src/FairPlaySocialSln/FairPlaySocial/Client/Shared/MainLayout.razor
src/FairPlaySocialSln/FairPlaySocial/Client/Shared/MainLayout.razor.cs
src/FairPlaySocialSln/FairPlaySocial/Client/wwwroot/index.html
src/FairPlaySocialSln/FairPlaySocial/Client/wwwroot/js/blazor-culture.js
src/FairPlaySocialSln/FairPlaySocial/Server/AutoMapperProfiles/ResourceProfile.cs
src/FairPlaySocialSln/FairPlaySocial/Server/Startup.cs
src/FairPlaySocialSln/FairPlaySocial/Server/Translations/BackgroundTranslationService.cs

Adding base for Automatic Translation and Culture Selection.
Solves #66

Integrate azure translator

---

src/FairPlaySocialSln/FairPlaySocial.SharedUI/Pages/Index.razor.cs

Creating the Resource Keys for the menu items

Adding localization for menu items

---

src/FairPlaySocialSln/FairPlaySocial.DataAccess/Data/FairPlaySocialDatabaseContext.cs
src/FairPlaySocialSln/FairPlaySocial.DataAccess/Models/Post.cs
src/FairPlaySocialSln/FairPlaySocial.Database/dbo/Tables/Post.sql
src/FairPlaySocialSln/FairPlaySocial/Server/Controllers/MyPostController.cs
src/FairPlaySocialSln/FairPlaySocial/Server/Controllers/PostCommentController.cs

Adding deletion of post replies by using a RootPostId approach
Solves #71

Adding Replies Delete

---

src/FairPlaySocialSln/FairPlaySocial/Client/Shared/MainLayout.razor.cs

Enabling localization of the Azure B2C Auth Flow
Solves Github Issue #72

Adding support for passing selected culture to the Azure AD B2C flow

---

src/FairPlaySocialSln/FairPlaySocial.Common/Handlers/LocalizationMessageHandler.cs
src/FairPlaySocialSln/FairPlaySocial.MAUIBlazor/MauiProgram.cs
src/FairPlaySocialSln/FairPlaySocial/Client/Program.cs

Fixing exception running MAUI App due to Localization Services not being registered

Fixing exception in MAUI app

---

.github/workflows/FairPlaySocialDev.yml
src/FairPlaySocialSln/FairPlaySocial.AutomatedPostDeploymentTests/FairPlaySocial.AutomatedPostDeploymentTests.csproj
src/FairPlaySocialSln/FairPlaySocial.AutomatedPostDeploymentTests/NavigateToRoot_Tests.cs
src/FairPlaySocialSln/FairPlaySocial.AutomatedPostDeploymentTests/PostDeploymentTestsBase.cs
src/FairPlaySocialSln/FairPlaySocial.AutomatedPostDeploymentTests/Usings.cs
src/FairPlaySocialSln/FairPlaySocialSln.sln

Adding Playwright as Post-Deployments Tests
Partially Solves Github Issue #76

Adding post deployment tests

---

src/FairPlaySocialSln/FairPlaySocial.AutomatedTests/ClientServices/ClientServicesTestsBase.cs
src/FairPlaySocialSln/FairPlaySocial.ClientServices/ClientSideErrorLogClientService.cs
src/FairPlaySocialSln/FairPlaySocial.ClientServices/VisitorTrackingClientService.cs
src/FairPlaySocialSln/FairPlaySocial.Common/CustomExceptions/CustomValidationException.cs
src/FairPlaySocialSln/FairPlaySocial.Common/CustomHelpers/DisplayHelper.cs
src/FairPlaySocialSln/FairPlaySocial.Models/Extensions/HttpResponseMessageExtensions.cs
src/FairPlaySocialSln/FairPlaySocial.Models/Post/CreatePostModel.cs
src/FairPlaySocialSln/FairPlaySocial.Services/ApplicationUserService.cs
src/FairPlaySocialSln/FairPlaySocial.Services/Utils/ExpressionUtils.cs
src/FairPlaySocialSln/FairPlaySocial.SharedUI/Components/ImagePicker.razor
src/FairPlaySocialSln/FairPlaySocial.SharedUI/Pages/User/Posts/CreateMyPost.razor
src/FairPlaySocialSln/FairPlaySocial.SharedUI/_Imports.razor
src/FairPlaySocialSln/FairPlaySocial/Client/Services/BlazorGeoLocationService.cs
src/FairPlaySocialSln/FairPlaySocial/Server/Controllers/MyFeedController.cs
src/FairPlaySocialSln/FairPlaySocial/Server/Controllers/MyFollowController.cs
src/FairPlaySocialSln/FairPlaySocial/Server/Controllers/MyPostController.cs
src/FairPlaySocialSln/FairPlaySocial/Server/Controllers/PostCommentController.cs
src/FairPlaySocialSln/FairPlaySocial/Server/Controllers/PublicFeedController.cs
src/FairPlaySocialSln/FairPlaySocial/Server/Controllers/PublicPhotoController.cs
src/FairPlaySocialSln/FairPlaySocial/Server/ExceptionsHelper.cs
src/FairPlaySocialSln/FairPlaySocial/Server/Program.cs

Integration of DisplayHelper
Solves Github Issue #88

Integrating the base for the DisplayHelper

---

src/FairPlaySocialSln/FairPlaySocial.MAUIBlazor/App.xaml.cs
src/FairPlaySocialSln/FairPlaySocial.MAUIBlazor/FairPlaySocial.MAUIBlazor.csproj
src/FairPlaySocialSln/FairPlaySocial.MAUIBlazor/Platforms/Android/MsalActivity.cs
src/FairPlaySocialSln/FairPlaySocial.MAUIBlazor/appsettings.Development.json
src/FairPlaySocialSln/FairPlaySocial.MAUIBlazor/appsettings.json

Adding integration with App Center
Solves Github Issue #77

Integrate app center

---

src/FairPlaySocialSln/FairPlaySocial.Models/Group/CreateGroupModel.cs
src/FairPlaySocialSln/FairPlaySocial.Models/Group/GroupModel.cs
src/FairPlaySocialSln/FairPlaySocial/Server/AutoMapperProfiles/GroupProfile.cs
src/FairPlaySocialSln/FairPlaySocial/Server/Controllers/MyGroupController.cs

Creating the MyGroupController
Solves Github Issue #49

Creating the MyGroupController

---

src/FairPlaySocialSln/FairPlaySocial.ClientServices/MyGroupClientService.cs
src/FairPlaySocialSln/FairPlaySocial.ClientsConfiguration/ClientsInitialization.cs

Adding MyGroupClientService
Solves Github Issue #50

Adding MyGroupClientService

---

src/FairPlaySocialSln/FairPlaySocial.ClientsConfiguration/ModelsLocalizationSetup.cs
src/FairPlaySocialSln/FairPlaySocial.Common/Global/Constants.cs
src/FairPlaySocialSln/FairPlaySocial.Common/Interfaces/Services/INavigationService.cs
src/FairPlaySocialSln/FairPlaySocial.DataAccess/Models/Group.partial.cs
src/FairPlaySocialSln/FairPlaySocial.Models/Group/CreateGroupModel.cs
src/FairPlaySocialSln/FairPlaySocial.MultiplatformServices/NavigationService.cs
src/FairPlaySocialSln/FairPlaySocial.SharedUI/Pages/Index.razor.cs
src/FairPlaySocialSln/FairPlaySocial.SharedUI/Pages/User/Groups/CreateMyGroup.razor
src/FairPlaySocialSln/FairPlaySocial.SharedUI/Pages/User/Groups/CreateMyGroup.razor.cs
src/FairPlaySocialSln/FairPlaySocial/Server/Controllers/MyGroupController.cs

Adding the page for "CreateMyGroup"
Solves Github Issue #96

Adding the base page for "CreateMyGroup"

---

src/FairPlaySocialSln/FairPlaySocial.Services/SearchService.cs
src/FairPlaySocialSln/FairPlaySocial/Server/PlatformServices.cs

Adding the base for the SearchService
Solves Github Issue #85

Adding the basic SearchService

---

src/FairPlaySocialSln/FairPlaySocial.Models/UserProfile/UserProfileModel.cs
src/FairPlaySocialSln/FairPlaySocial/Server/AutoMapperProfiles/UserProfileProfile.cs
src/FairPlaySocialSln/FairPlaySocial/Server/Controllers/SearchController.cs

Creating the base for the SearchController
Solves Github Issue #100

Adding base for the SearchController

---

src/FairPlaySocialSln/FairPlaySocial.ClientServices/SearchClientService.cs
src/FairPlaySocialSln/FairPlaySocial.ClientsConfiguration/ClientsInitialization.cs

Created the basic implementation of the SearchClientService
Solves Github Issue #102

Adding the SearchClientService

---

src/FairPlaySocialSln/FairPlaySocial.ClientServices/SearchClientService.cs
src/FairPlaySocialSln/FairPlaySocial.Common/Global/Constants.cs
src/FairPlaySocialSln/FairPlaySocial.Common/Interfaces/Services/INavigationService.cs
src/FairPlaySocialSln/FairPlaySocial.Models/Search/SearchModel.cs
src/FairPlaySocialSln/FairPlaySocial.MultiplatformComponents/Bootstrap/Card.razor
src/FairPlaySocialSln/FairPlaySocial.MultiplatformComponents/Bootstrap/Card.razor.cs
src/FairPlaySocialSln/FairPlaySocial.MultiplatformServices/NavigationService.cs
src/FairPlaySocialSln/FairPlaySocial.SharedUI/Components/SearchModal.razor
src/FairPlaySocialSln/FairPlaySocial.SharedUI/Components/SearchModal.razor.cs
src/FairPlaySocialSln/FairPlaySocial.SharedUI/Pages/User/Search/SearchUserProfiles.razor
src/FairPlaySocialSln/FairPlaySocial.SharedUI/Pages/User/Search/SearchUserProfiles.razor.cs
src/FairPlaySocialSln/FairPlaySocial/Client/Shared/MainLayout.razor

Implementation of the basic search pages and modal
Solves Github Issue #104

Implementing the basic Search from the UI

---

.github/workflows/Dev_Branch_Build.yml
.github/workflows/FairPlaySocialDev.yml
src/FairPlaySocialSln/FairPlaySocial.MAUIBlazor/Shared/MainLayout.razor

Adding the search component into the maui app
Solves Github Issue #106

Adding the search component to the maui app

---

src/FairPlaySocialSln/FairPlaySocial/Client/FairPlaySocial.Client.csproj

Updating Blazored Toast to latest version
Solves Github Issue #108

Updating the BlazoredToast Library

---

src/FairPlaySocialSln/FairPlaySocial.SharedUI/Components/SearchModal.razor
src/FairPlaySocialSln/FairPlaySocial.SharedUI/Pages/User/Search/SearchGroups.razor
src/FairPlaySocialSln/FairPlaySocial.SharedUI/Pages/User/Search/SearchGroups.razor.cs

Creating the SearchGroup Page
Solves Github Issue #110

Creating the SearchGroups page

---

src/FairPlaySocialSln/FairPlaySocial.ClientServices/MyGroupClientService.cs
src/FairPlaySocialSln/FairPlaySocial.DataAccess/Data/FairPlaySocialDatabaseContext.cs
src/FairPlaySocialSln/FairPlaySocial.DataAccess/Models/Group.cs
src/FairPlaySocialSln/FairPlaySocial.DataAccess/Models/GroupMember.cs
src/FairPlaySocialSln/FairPlaySocial.DataAccess/Models/GroupMember.partial.cs
src/FairPlaySocialSln/FairPlaySocial.Database/dbo/Tables/GroupMember.sql
src/FairPlaySocialSln/FairPlaySocial.MAUIBlazor/wwwroot/index.html
src/FairPlaySocialSln/FairPlaySocial.Services/GroupMemberService.cs
src/FairPlaySocialSln/FairPlaySocial.SharedUI/Pages/User/Search/SearchGroups.razor
src/FairPlaySocialSln/FairPlaySocial.SharedUI/Pages/User/Search/SearchGroups.razor.cs
src/FairPlaySocialSln/FairPlaySocial/Client/wwwroot/index.html
src/FairPlaySocialSln/FairPlaySocial/Server/Controllers/MyGroupController.cs
src/FairPlaySocialSln/FairPlaySocial/Server/PlatformServices.cs

Enabling the ability to join groups
Solves Github Issue #112

Enabling the ability to join groups

---

src/FairPlaySocialSln/FairPlaySocial.ClientServices/MyFeedClientService.cs
src/FairPlaySocialSln/FairPlaySocial.Common/Global/Constants.cs
src/FairPlaySocialSln/FairPlaySocial.Common/Interfaces/Services/IAnalyticsService.cs
src/FairPlaySocialSln/FairPlaySocial.Common/Interfaces/Services/INavigationService.cs
src/FairPlaySocialSln/FairPlaySocial.DataAccess/Data/FairPlaySocialDatabaseContext.cs
src/FairPlaySocialSln/FairPlaySocial.DataAccess/Models/Group.cs
src/FairPlaySocialSln/FairPlaySocial.DataAccess/Models/Post.cs
src/FairPlaySocialSln/FairPlaySocial.Database/dbo/Tables/Post.sql
src/FairPlaySocialSln/FairPlaySocial.Models/Post/CreatePostModel.cs
src/FairPlaySocialSln/FairPlaySocial.Models/Post/CreateSharedPostModel.cs
src/FairPlaySocialSln/FairPlaySocial.Models/Post/PostModel.cs
src/FairPlaySocialSln/FairPlaySocial.MultiplatformServices/NavigationService.cs
src/FairPlaySocialSln/FairPlaySocial.SharedUI/Components/PostComponent.razor.cs
src/FairPlaySocialSln/FairPlaySocial.SharedUI/Pages/User/Feeds/GroupFeed.razor
src/FairPlaySocialSln/FairPlaySocial.SharedUI/Pages/User/Feeds/GroupFeed.razor.cs
src/FairPlaySocialSln/FairPlaySocial.SharedUI/Pages/User/Posts/CreateMyPost.razor.cs
src/FairPlaySocialSln/FairPlaySocial.SharedUI/Pages/User/Search/SearchGroups.razor
src/FairPlaySocialSln/FairPlaySocial.SharedUI/Pages/User/Search/SearchGroups.razor.cs
src/FairPlaySocialSln/FairPlaySocial/Server/Controllers/MyFeedController.cs
src/FairPlaySocialSln/FairPlaySocial/Server/Controllers/MyPostController.cs

Implemeting the GroupFeed page.
Adding ability to create posts in groups
Solves Github Issue #114

Adding group feed

---

src/FairPlaySocialSln/FairPlaySocial.Common/Global/Constants.cs
src/FairPlaySocialSln/FairPlaySocial/Server/Controllers/MyFeedController.cs
src/FairPlaySocialSln/FairPlaySocial/Server/Startup.cs

Adding basic Rate Limit to Home Feed
Solves Github Issue #116

Adding Server Rate Limit

---

src/FairPlaySocialSln/FairPlaySocial.Common/Global/Constants.cs
src/FairPlaySocialSln/FairPlaySocial/Server/Controllers/LocalizationController.cs
src/FairPlaySocialSln/FairPlaySocial/Server/OutputCacheExtensions.cs
src/FairPlaySocialSln/FairPlaySocial/Server/RateLimiterExtensions.cs
src/FairPlaySocialSln/FairPlaySocial/Server/Startup.cs

Introducing Output Caching for Localization endpoints
Solves Github Issue #118

Introducing Output Caching for Localization Endpoints

---

src/FairPlaySocialSln/FairPlaySocial.MAUIBlazor/App.xaml.cs
src/FairPlaySocialSln/FairPlaySocial.MAUIBlazor/FairPlaySocial.MAUIBlazor.csproj
src/FairPlaySocialSln/FairPlaySocial.MAUIBlazor/MauiProgram.cs
src/FairPlaySocialSln/FairPlaySocial.MAUIBlazor/MultiPlatformServices/BlazorToastService.cs
src/FairPlaySocialSln/FairPlaySocial.MAUIBlazor/MultiPlatformServices/MauiToastService.cs
src/FairPlaySocialSln/FairPlaySocial.MAUIBlazor/Shared/MainLayout.razor
src/FairPlaySocialSln/FairPlaySocial.MAUIBlazor/_Imports.razor
src/FairPlaySocialSln/FairPlaySocial.MAUIBlazor/wwwroot/index.html

Fixing issue on Windows Build not intializing b2CConstants.PublicClientApp
Making MAUI use Blazored.Toast
Solves Github Issue #145

Making MAUI use Blazored Toast

---

src/FairPlaySocialSln/FairPlaySocial.ClientServices/VisitorTrackingClientService.cs
src/FairPlaySocialSln/FairPlaySocial.MAUIBlazor/FairPlaySocial.MAUIBlazor.csproj
src/FairPlaySocialSln/FairPlaySocial.Services/VisitorTrackingService.cs
src/FairPlaySocialSln/FairPlaySocial.SharedUI/Pages/Public/Embedded/Post.razor
src/FairPlaySocialSln/FairPlaySocial.SharedUI/Pages/Public/Embedded/Post.razor.cs
src/FairPlaySocialSln/FairPlaySocial/Client/App.razor
src/FairPlaySocialSln/FairPlaySocial/Client/Program.cs
src/FairPlaySocialSln/FairPlaySocial/Client/Shared/MainLayout.razor
src/FairPlaySocialSln/FairPlaySocial/Client/wwwroot/index.html
src/FairPlaySocialSln/FairPlaySocial/Server/Controllers/OpenGraphController.cs
src/FairPlaySocialSln/FairPlaySocial/Server/FairPlaySocial.Server.csproj
src/FairPlaySocialSln/FairPlaySocial/Server/Pages/_Host.cshtml
src/FairPlaySocialSln/FairPlaySocial/Server/Startup.cs

Adding the basis for Blazor WebAssembly Pre-Rendering and OpenGraph Support
Solves Github Issue #147

Add pre rendering

---

src/FairPlaySocialSln/FairPlaySocial.DataAccess/Models/UserProfile.cs
src/FairPlaySocialSln/FairPlaySocial.Database/dbo/Tables/UserProfile.sql
src/FairPlaySocialSln/FairPlaySocial.Models/UserProfile/CreateUserProfileModel.cs
src/FairPlaySocialSln/FairPlaySocial.Models/UserProfile/UserProfileModel.cs
src/FairPlaySocialSln/FairPlaySocial.SharedUI/Components/PostComponent.razor
src/FairPlaySocialSln/FairPlaySocial.SharedUI/Pages/User/UserProfile/UpdateMyUserProfile.razor
src/FairPlaySocialSln/FairPlaySocial.SharedUI/Pages/User/UserProfile/UpdateMyUserProfile.razor.cs
src/FairPlaySocialSln/FairPlaySocial/Client/Shared/RedirectToLogin.razor
src/FairPlaySocialSln/FairPlaySocial/Server/Controllers/MyUserProfileController.cs

Enabling support for Github sponsors button
Solves Github Issue #152

Enabling Github Sponsors button

---

src/FairPlaySocialSln/FairPlaySocial.SharedUI/Pages/Index.razor.cs

Optimizing initial load
Solves Github Issue #154

Optimizing intiial load.
